language: cpp
os:
  - linux
  - osx
matrix:
  fast_finish: true
  allow_failures:
    - os: osx  
compiler:
  - gcc
  - clang
  - CXX=mingw; export CXX; true

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "UE8I6ubHMARmKBNBtDDW34DI+PlFe/g2XR4DStfAg34R193nevkpDj+WqBN88VCxN9Z57CMI5fweQUc6r5L5ZuQns8XKe4lu0AmtroOHf+e/FUDlSGz9DUZZk6oTwEtKrsg548ZTanU+fiFkwbvKwx/nHLdYzsI8PYgmw7vci8w="

addons:
  coverity_scan:
    project:
      name: "OpenTechEngine/OpenTechBFG"
      description: "Build submitted via Travis CI"
    notification_email: kordex@gmail.com
    build_command_prepend: 'mkdir build && cd build &&  if [ \"$CXX\" = \"mingw\" ]; then cmake -G \"Eclipse CDT4 - Unix Makefiles\" -DCMAKE_TOOLCHAIN_FILE=../scripts/mingw32.toolchain.cmake -DCMAKE_BUILD_TYPE=Debug -DSDL2=OFF -DBUNDLED_FREETYPE=ON -DBUNDLED_OPENAL=ON ../ ;else cmake -G \"Eclipse CDT4 - Unix Makefiles\" -DCMAKE_BUILD_TYPE=Debug -DSDL2=OFF ../;fi'
    build_command:   "make -j 9"
    branch_pattern: coverity

before_install:
  # this is allowed to fail so that pull requests can be built too
  - openssl aes-256-cbc -K $encrypted_24fdd259e571_key -iv $encrypted_24fdd259e571_iv -in .travis/id_rsa.enc -out .travis/id_rsa -d || true

install:
 - if [ "$TRAVIS_OS_NAME" = "linux" ]; then bash .travis/scripts/install.ubuntu.sh ; fi
 - if [ "$TRAVIS_OS_NAME" = "osx" ]; then bash .travis/scripts/install.osx.sh ; fi

script: 
 - mkdir -p build && cd build
 - if [ "$CXX" = "mingw" ]; then cmake -G "Eclipse CDT4 - Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE=../scripts/mingw32.toolchain.cmake -DCMAKE_BUILD_TYPE=Debug -DSDL2=OFF -DBUNDLED_FREETYPE=ON -DBUNDLED_OPENAL=ON ../ ;else cmake -G "Eclipse CDT4 - Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug -DSDL2=OFF ../;fi
 - make

after_success:
 - make package || true
 - cd ..
 - if [ "$CXX" = "g++" ]; then bash .travis/scripts/after_success.gcc.sh || true; fi
 - if [ "$CXX" = "clang++" ]; then bash .travis/scripts/after_success.clang.sh || true; fi
 - if [ "$CXX" = "mingw" ]; then bash .travis/scripts/after_success.mingw.sh || true; fi

after_failure:
 - bash .travis/scripts/after_failure.sh

deploy:
  provider: releases
  api_key:
    secure: CqNzdXDsCrmC8v7XaJEWARDOq2RcuRqsiAv/32TBgC681767jlC7zYFJHxAvrvx3iPTTlW3fsqiNEDhsqnraArO7M4CMOV9lEssZAJoMV25gWkNNqBwjwfLeS5VCmZPwrznXR4qfKMIsIHaKZNDEQiSlvd4PP8M0z5mDjh5oims=
  file: "$TRAVIS_BUILD_DIR/build/OpenTechBFG-1.0.0-win32.exe"
  skip_cleanup: true
  on:
    repo: "OpenTechEngine/OpenTechBFG"
    tags: true
    condition: $CXX = "mingw"
